name: Pixel7Pro-Android13-5.10

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget unzip python3 flex bison build-essential bc curl

    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
        chmod a+x /usr/local/bin/repo
        repo --version

    - name: Sync Pixel 7 Pro kernel source
      run: |
        mkdir pixel-kernel && cd pixel-kernel
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b android13-5.10-c2
        repo sync -j$(nproc)
        cd ..

    - name: Apply patches and config (LXC/Docker)
      run: |
        git clone https://github.com/RONNIE158/GKI-Custom.git gki-patch
        cp ./gki-patch/config/gki_defconfig ./pixel-kernel/common/arch/arm64/configs/gki_defconfig
        cd ./pixel-kernel/common
        git apply ../../gki-patch/patchs/*.patch || true
        cd ../..

    - name: Enable KernelSU
      run: |
        cd pixel-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        cd ..

    - name: Build Kernel
      run: |
        cd pixel-kernel
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
        cd ..

    - name: Pack boot.img
      run: |
        cd pixel-kernel
        wget https://dl.google.com/android/gki/gki-certified-boot-android13-5.10-2023-05_r1.zip -O ../gki-certified-boot.zip
        unzip -q ../gki-certified-boot.zip
        ./tools/mkbootimg/unpack_bootimg.py --boot_img ../boot-5.10.img
        ./tools/mkbootimg/mkbootimg.py --header_version 4 \
          --kernel out/android13-5.10/dist/Image \
          --ramdisk out/ramdisk \
          --os_version 13.0.0 \
          --os_patch_level 2023-11 \
          -o ../pixel7pro-android13-boot.img
        cd ..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Pixel7Pro-Android13-Kernel
        path: ./pixel7pro-android13-boot.img
