name: Build Pixel 7 Pro Kernel (Android 13 - 5.10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential curl flex g++-multilib gcc-multilib git \
            gnupg gperf imagemagick lib32ncurses-dev libncurses5-dev \
            libssl-dev libxml2-utils lzop pngcrush rsync schedtool \
            squashfs-tools xsltproc zip zlib1g-dev unzip wget \
            python3 python3-pip python-is-python3 ccache

      - name: Sync Pixel 7 Pro kernel source
        run: |
          mkdir pixel-kernel && cd pixel-kernel
          repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b android13-5.10-c2
          repo sync -j$(nproc)
          cd ..

      - name: Apply LXC/Docker configs
        run: |
          git clone https://github.com/TapetalArray/gki-lxc
          cp ./gki-lxc/gki_defconfig ./pixel-kernel/private/gs-google/arch/arm64/configs/gki_defconfig
          cd pixel-kernel/private/gs-google
          git apply ../../../gki-lxc/*.patch || true
          cd ../../..

      - name: Build Kernel
        run: |
          cd pixel-kernel
          BUILD_CONFIG=private/gs-google/build.config.gki.aarch64 build/build.sh
          cd ..

      - name: Package boot.img
        run: |
          cd pixel-kernel
          ./tools/mkbootimg/mkbootimg.py \
            --header_version 4 \
            --kernel out/android13-5.10/dist/Image.lz4 \
            --ramdisk out/ramdisk \
            --dtb out/android13-5.10/dist/dtb.img \
            --os_version 13.0.0 \
            --os_patch_level 2023-11 \
            -o ../pixel7pro-android13-boot-lxc.img
          cd ..

      - name: Pack AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git
          cp ./pixel-kernel/out/android13-5.10/dist/Image.lz4 ./AnyKernel3/Image.lz4
          cp ./pixel-kernel/out/android13-5.10/dist/dtb.img ./AnyKernel3/dtb.img
          cd AnyKernel3
          zip -r -q ../AnyKernel3-pixel7pro-android13-lxc.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pixel7Pro-Android13-Kernel
          path: AnyKernel3-pixel7pro-android13-lxc.zip
